name: dm-lab1
channels:
  - conda-forge
platforms:
  - linux-64
dependencies:
  - python=3.9.6
  - pip
  - jupyter
  - scikit-learn
  - numpy
  - matplotlib
  - plotly
  - seaborn
  - nltk
# dev dependencies:
  - flake8
  - black
  - ipykernel
  - mypy
  - types-requests
